<?php

use Illuminate\Database\Seeder;

class CitiesSeeder extends Seeder
{

    public function run()
    {
      DB::table('cities')->delete();
      $date = date('Y-m-d H:i:s');
      $cities = [
            ['id' => 2, 'name' => 'Acaraguá' ,'state_id' => 13, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 3, 'name' => 'Acassuso' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 4, 'name' => 'Acevedo' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 5, 'name' => 'Adelia María' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 6, 'name' => 'Agrelo' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 7, 'name' => 'Aguilares' ,'state_id' => 21, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 8, 'name' => 'Aimogasta' ,'state_id' => 11, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 9, 'name' => 'Albardón' ,'state_id' => 17, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 10, 'name' => 'Alberti' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 11, 'name' => 'Aldea Escolar' ,'state_id' => 4, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 12, 'name' => 'Alderetes' ,'state_id' => 21, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 13, 'name' => 'Allen' ,'state_id' => 14, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 14, 'name' => 'Almafuerte' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 16, 'name' => 'Alto de Sierra' ,'state_id' => 17, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 17, 'name' => 'Alto Río Senguerr' ,'state_id' => 4, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 18, 'name' => 'Alto Verde' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 19, 'name' => 'Alvarez' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 20, 'name' => 'Alvear' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 21, 'name' => 'Añatuya' ,'state_id' => 19, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 22, 'name' => 'Ancón' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 23, 'name' => 'Andacollo' ,'state_id' => 21, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 24, 'name' => 'Andalgalá' ,'state_id' => 2, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 25, 'name' => 'Añelo' ,'state_id' => 21, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 26, 'name' => 'Angaco' ,'state_id' => 17, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 27, 'name' => 'Apolinario Saravia' ,'state_id' => 15, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 28, 'name' => 'Apostoles' ,'state_id' => 13, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 29, 'name' => 'Aranguren' ,'state_id' => 7, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 30, 'name' => 'Arias' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 31, 'name' => 'Aristóbulo del Valle' ,'state_id' => 13, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 32, 'name' => 'Armstrong' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 33, 'name' => 'Arrecifes' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 34, 'name' => 'Arroyito' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 37, 'name' => 'Atucha' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 38, 'name' => 'Avellaneda' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 39, 'name' => 'Avellaneda' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 40, 'name' => 'Azul' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 41, 'name' => 'Bahía Blanca' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 42, 'name' => 'Bahia San Blas' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 43, 'name' => 'Bajo Grande' ,'state_id' => 11, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 44, 'name' => 'Bajo Hondo' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 45, 'name' => 'Balcarce' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 46, 'name' => 'Ballesteros' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 47, 'name' => 'Banda del Río Salí' ,'state_id' => 21, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 48, 'name' => 'Banfield' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 49, 'name' => 'Baradero' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 50, 'name' => 'Barrancas' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 51, 'name' => 'Barranqueras' ,'state_id' => 3, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 52, 'name' => 'Barreal' ,'state_id' => 17, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 53, 'name' => 'Barrio Batan' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 54, 'name' => 'Barrio Marquez de Sobremonte' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 55, 'name' => 'Beccar' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 56, 'name' => 'Belén de Escobar' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 57, 'name' => 'Bell Ville' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 58, 'name' => 'Bella Vista' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 59, 'name' => 'Bella Vista' ,'state_id' => 21, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 60, 'name' => 'Bella Vista' ,'state_id' => 6, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 61, 'name' => 'Benavidez' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 62, 'name' => 'Bengolea' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 63, 'name' => 'Benito Juarez' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 64, 'name' => 'Berazategui' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 65, 'name' => 'Bernal' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 66, 'name' => 'Bombal' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 67, 'name' => 'Boulogne' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 68, 'name' => 'Bowen' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 69, 'name' => 'Bragado' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 70, 'name' => 'Brandsen' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 72, 'name' => 'Burruyacú' ,'state_id' => 21, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 73, 'name' => 'Burzaco' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 74, 'name' => 'Caballito' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 76, 'name' => 'Cafayate' ,'state_id' => 15, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 77, 'name' => 'Calabacillas' ,'state_id' => 7, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 78, 'name' => 'Caleta Córdoba' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 79, 'name' => 'Caleta Olivia' ,'state_id' => 6, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 80, 'name' => 'Campana' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 81, 'name' => 'Campo Grande' ,'state_id' => 13, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 82, 'name' => 'Campo Largo' ,'state_id' => 3, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 83, 'name' => 'Campo Quijano' ,'state_id' => 15, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 84, 'name' => 'Campo Ramón' ,'state_id' => 13, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 85, 'name' => 'Campo Salto' ,'state_id' => 15, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 86, 'name' => 'Campo Santo' ,'state_id' => 15, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 87, 'name' => 'Campo Viera' ,'state_id' => 13, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 88, 'name' => 'Cañada de Gómez' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 89, 'name' => 'Canada Rosquin' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 90, 'name' => 'Canals' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 91, 'name' => 'Candelaria' ,'state_id' => 13, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 92, 'name' => 'Canning' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 93, 'name' => 'Canuelas' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 94, 'name' => 'Capilla del Señor' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 96, 'name' => 'Capitán Sarmiento' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 97, 'name' => 'Carcaraña' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 98, 'name' => 'Carlos Casares' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 99, 'name' => 'Carmen de Areco' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 100, 'name' => 'Carmen de Patagones' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 101, 'name' => 'Carmen Del Sauce' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 102, 'name' => 'Carnerillo' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 103, 'name' => 'Caseros' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 104, 'name' => 'Casilda' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 105, 'name' => 'Castelar' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 106, 'name' => 'Catamarca' ,'state_id' => 2, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 107, 'name' => 'Catinzaco' ,'state_id' => 11, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 108, 'name' => 'Catrilo' ,'state_id' => 10, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 109, 'name' => 'Caucete' ,'state_id' => 17, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 110, 'name' => 'Caviahue' ,'state_id' => 21, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 111, 'name' => 'Centenario' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 112, 'name' => 'Ceres' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 113, 'name' => 'Cerro Azul' ,'state_id' => 13, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 114, 'name' => 'Cevil Pozo' ,'state_id' => 21, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 115, 'name' => 'Cevil Redondo' ,'state_id' => 21, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 116, 'name' => 'Chabás' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 117, 'name' => 'Chacabuco' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 118, 'name' => 'Chacras De Coria' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 119, 'name' => 'Chajarí' ,'state_id' => 7, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 120, 'name' => 'Charata' ,'state_id' => 3, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 121, 'name' => 'Chascomus' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 122, 'name' => 'Chilecito' ,'state_id' => 11, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 123, 'name' => 'Chimbas' ,'state_id' => 17, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 124, 'name' => 'Chimpay' ,'state_id' => 14, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 125, 'name' => 'Chivilcoy' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 126, 'name' => 'Choele Choel' ,'state_id' => 14, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 127, 'name' => 'Chos Malal' ,'state_id' => 21, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 128, 'name' => 'Cinco Saltos' ,'state_id' => 14, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 129, 'name' => 'Cipoletti' ,'state_id' => 14, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 130, 'name' => 'City Bell' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 131, 'name' => 'Ciudad Evita' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 132, 'name' => 'Ciudadela' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 133, 'name' => 'Classon' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 134, 'name' => 'Clorinda' ,'state_id' => 11, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 135, 'name' => 'Colazo' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 136, 'name' => 'Colón' ,'state_id' => 7, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 137, 'name' => 'Colón' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 138, 'name' => 'Colonia Caroya' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 139, 'name' => 'Colonia Catriel' ,'state_id' => 14, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 140, 'name' => 'Colonia Sarmiento' ,'state_id' => 4, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 141, 'name' => 'Comodoro Rivadavia' ,'state_id' => 4, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 142, 'name' => 'Concepción' ,'state_id' => 6, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 143, 'name' => 'Concepcion de la Sierra' ,'state_id' => 13, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 144, 'name' => 'Concepción del Uruguay' ,'state_id' => 7, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 145, 'name' => 'Conceptión' ,'state_id' => 21, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 146, 'name' => 'Concordia' ,'state_id' => 7, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 147, 'name' => 'Contralmirante Martín Guerrico' ,'state_id' => 14, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 148, 'name' => 'Coquimbito' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 149, 'name' => 'Córdoba' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 150, 'name' => 'Coronda' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 151, 'name' => 'Coronel Suarez' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 152, 'name' => 'Corrientes' ,'state_id' => 6, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 153, 'name' => 'Costa de Araujo' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 154, 'name' => 'Crespo' ,'state_id' => 7, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 155, 'name' => 'Cruz Alta' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 156, 'name' => 'Cruz De Piedra' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 157, 'name' => 'Cruz del Eje' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 158, 'name' => 'Cuadro Nacional' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 159, 'name' => 'Cuatreros/Bahia Blanca' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 160, 'name' => 'Curuzú Cuatiá' ,'state_id' => 6, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 161, 'name' => 'Cutral-Có' ,'state_id' => 21, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 162, 'name' => 'Daireaux' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 163, 'name' => 'Del Guazu' ,'state_id' => 7, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 164, 'name' => 'Del Viso' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 165, 'name' => 'Diamante' ,'state_id' => 14, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 166, 'name' => 'Dock Sud' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 167, 'name' => 'Dock Sur' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 168, 'name' => 'Don Torcuato' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 169, 'name' => 'Dorrego' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 170, 'name' => 'El Bolsón' ,'state_id' => 14, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 171, 'name' => 'El Bolsón' ,'state_id' => 2, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 172, 'name' => 'El Bordo' ,'state_id' => 15, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 173, 'name' => 'El Calafate' ,'state_id' => 6, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 174, 'name' => 'El Carril' ,'state_id' => 15, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 175, 'name' => 'El Maitén' ,'state_id' => 4, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 176, 'name' => 'El Palomar' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 177, 'name' => 'El Plumerillo' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 178, 'name' => 'El Talar de Pacheco' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 179, 'name' => 'El Trébol' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 180, 'name' => 'Eldorado' ,'state_id' => 13, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 181, 'name' => 'Embarcacíon' ,'state_id' => 15, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 182, 'name' => 'Ensenada' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 183, 'name' => 'Espeleta' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 184, 'name' => 'Esperanza' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 185, 'name' => 'Esquel' ,'state_id' => 4, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 186, 'name' => 'Esteban Echeverría' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 187, 'name' => 'Etruria' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 188, 'name' => 'Eugenio Bustos' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 189, 'name' => 'Ezeiza' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 190, 'name' => 'Famaillá' ,'state_id' => 21, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 191, 'name' => 'Federación' ,'state_id' => 7, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 192, 'name' => 'Fernández' ,'state_id' => 19, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 193, 'name' => 'Ferreyra' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 194, 'name' => 'Florencio Varela' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 195, 'name' => 'Florida' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 196, 'name' => 'Formosa' ,'state_id' => 9, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 197, 'name' => 'Franck' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 198, 'name' => 'Fray Luis A. Beltrán' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 199, 'name' => 'Fray Luis Beltran' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 200, 'name' => 'Freyre' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 201, 'name' => 'Frontera' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 202, 'name' => 'Fuentes' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 203, 'name' => 'Funes' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 204, 'name' => 'Gálvez' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 205, 'name' => 'Garín' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 206, 'name' => 'General Alvear' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 207, 'name' => 'General Belgrano' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 208, 'name' => 'General Cabrera' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 209, 'name' => 'General Deheza' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 210, 'name' => 'General Enrique Godoy' ,'state_id' => 14, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 211, 'name' => 'General Enrique Mosconi' ,'state_id' => 15, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 212, 'name' => 'General Güemes' ,'state_id' => 15, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 213, 'name' => 'General Gutiérrez' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 214, 'name' => 'General Lagos' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 215, 'name' => 'General Lavalle' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 216, 'name' => 'General Madariaga' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 217, 'name' => 'General Pacheco' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 218, 'name' => 'General Pico' ,'state_id' => 10, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 219, 'name' => 'General Ramírez' ,'state_id' => 7, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 220, 'name' => 'General Roca' ,'state_id' => 14, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 221, 'name' => 'General Rodríguez' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 222, 'name' => 'General Villegas' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 223, 'name' => 'Gerli' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 224, 'name' => 'Gobernador Benegas' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 225, 'name' => 'Gobernador Crespo' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 226, 'name' => 'Gobernador Gregores' ,'state_id' => 6, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 227, 'name' => 'Gobernador Roca' ,'state_id' => 13, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 228, 'name' => 'Godoy Cruz' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 229, 'name' => 'Gowland' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 230, 'name' => 'Goya' ,'state_id' => 6, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 231, 'name' => 'Granadero Baigorria' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 232, 'name' => 'Grand Bourg' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 233, 'name' => 'Gualeguay' ,'state_id' => 7, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 234, 'name' => 'Gualeguaychú' ,'state_id' => 7, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 235, 'name' => 'Guaymallén' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 236, 'name' => 'Güemes' ,'state_id' => 21, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 237, 'name' => 'Guerrico' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 238, 'name' => 'Haedo' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 239, 'name' => 'Hernando' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 240, 'name' => 'Herrera Vegas' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 241, 'name' => 'Hickmann' ,'state_id' => 15, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 242, 'name' => 'Hughes' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 243, 'name' => 'Humboldt' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 244, 'name' => 'Hurlingham' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 245, 'name' => 'Ibicuy' ,'state_id' => 7, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 246, 'name' => 'Iguazú' ,'state_id' => 13, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 247, 'name' => 'Ingeniero Allan' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 248, 'name' => 'Ingeniero Giagnoni' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 249, 'name' => 'Ingeniero J. Allan' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 250, 'name' => 'Ingeniero Jacobacci' ,'state_id' => 14, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 251, 'name' => 'Ingeniero Luis A. Huergo' ,'state_id' => 14, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 252, 'name' => 'Ingeniero Maschwitz' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 253, 'name' => 'Ingeniero White/Bahia Blanca' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 254, 'name' => 'Ireneo Portela' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 255, 'name' => 'Isidro Casanova' ,'state_id' => 2, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 256, 'name' => 'Ituzaingo' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 257, 'name' => 'Jauregui' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 258, 'name' => 'Jorge Newbury Apt/Buenos Aires' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 259, 'name' => 'José C. Paz' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 260, 'name' => 'José de San Martín' ,'state_id' => 4, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 261, 'name' => 'Jose Leon Suarez' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 262, 'name' => 'Juárez Celman' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 263, 'name' => 'Jujuy' ,'state_id' => 9, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 264, 'name' => 'Junin' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 265, 'name' => 'Junín' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 266, 'name' => 'Junín de Los Andes' ,'state_id' => 21, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 267, 'name' => 'La Calera' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 268, 'name' => 'La Carlota' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 269, 'name' => 'La Consulta' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 270, 'name' => 'La Cumbre' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 271, 'name' => 'La Escondida' ,'state_id' => 3, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 272, 'name' => 'La Falda' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 273, 'name' => 'La Paz' ,'state_id' => 7, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 274, 'name' => 'La Paz' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 275, 'name' => 'La Plata' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 276, 'name' => 'La Quiaca' ,'state_id' => 9, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 277, 'name' => 'La Reja' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 278, 'name' => 'La Rioja' ,'state_id' => 11, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 279, 'name' => 'La Tablada' ,'state_id' => 19, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 280, 'name' => 'La Toma' ,'state_id' => 16, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 281, 'name' => 'Laferrere' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 282, 'name' => 'Lago Argentino' ,'state_id' => 6, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 283, 'name' => 'Lanús' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 284, 'name' => 'Larroque' ,'state_id' => 7, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 285, 'name' => 'Las Catitas' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 286, 'name' => 'Las Compuertas' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 287, 'name' => 'Las Heras' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 288, 'name' => 'Las Heras' ,'state_id' => 6, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 289, 'name' => 'Las Higueras' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 290, 'name' => 'Las Lomitas' ,'state_id' => 9, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 291, 'name' => 'Las Palmas' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 292, 'name' => 'Las Paredes' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 293, 'name' => 'Las Parejas' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 294, 'name' => 'Las Varillas' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 295, 'name' => 'Lavalle' ,'state_id' => 2, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 296, 'name' => 'Leandro N. Alem' ,'state_id' => 13, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 297, 'name' => 'Ledesma' ,'state_id' => 9, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 298, 'name' => 'León Rouges' ,'state_id' => 21, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 299, 'name' => 'Lezama (Manuel J. Cobo)' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 300, 'name' => 'Lima' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 301, 'name' => 'Llavallol' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 302, 'name' => 'Loberia' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 303, 'name' => 'Loma Hermosa' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 304, 'name' => 'Lomas de Zamora' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 305, 'name' => 'Lomas del Mirador' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 306, 'name' => 'Loncopué' ,'state_id' => 21, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 307, 'name' => 'Los Boulevares' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 308, 'name' => 'Los Charrúas' ,'state_id' => 7, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 309, 'name' => 'Los Menucos' ,'state_id' => 14, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 310, 'name' => 'Los Polvorines' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 311, 'name' => 'Luis Guillon' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 312, 'name' => 'Luján' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 313, 'name' => 'Lujan de Cuyo' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 314, 'name' => 'Lules' ,'state_id' => 21, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 315, 'name' => 'Luque' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 316, 'name' => 'Luzuriaga' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 317, 'name' => 'Magdalena' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 318, 'name' => 'Mainque' ,'state_id' => 14, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 319, 'name' => 'Maipú' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 320, 'name' => 'Malargüe' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 321, 'name' => 'Manuel B. Gonnet' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 322, 'name' => 'Maquinchao' ,'state_id' => 14, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 323, 'name' => 'Mar del Plata' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 324, 'name' => 'Marcos Juarez' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 325, 'name' => 'Maria Grande' ,'state_id' => 7, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 326, 'name' => 'Mariano J. Haedo' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 327, 'name' => 'Martin Coronado' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 328, 'name' => 'Martínez' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 329, 'name' => 'Mataderos' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 330, 'name' => 'Matheu' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 331, 'name' => 'Mayor Drummond' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 332, 'name' => 'Medanitos' ,'state_id' => 2, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 333, 'name' => 'Melchor Romero' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 334, 'name' => 'Mendoza' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 335, 'name' => 'Mercedes' ,'state_id' => 6, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 336, 'name' => 'Merlo' ,'state_id' => 16, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 337, 'name' => 'Milagro' ,'state_id' => 11, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 338, 'name' => 'Ministro Pistarini Apt/Buenos Aires' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 339, 'name' => 'Miramar' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 340, 'name' => 'Mocoretá' ,'state_id' => 6, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 342, 'name' => 'Monte Caseros' ,'state_id' => 6, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 343, 'name' => 'Monte Chingolo' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 344, 'name' => 'Monte Cristo' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 345, 'name' => 'Monte Grand' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 346, 'name' => 'Monte Maíz' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 347, 'name' => 'Monte Quemado' ,'state_id' => 19, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 348, 'name' => 'Montecarlo' ,'state_id' => 13, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 349, 'name' => 'Moquehuá' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 350, 'name' => 'Moreno' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 352, 'name' => 'Mosconi' ,'state_id' => 15, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 353, 'name' => 'Munro' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 354, 'name' => 'Naschel' ,'state_id' => 16, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 355, 'name' => 'Navarro' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 356, 'name' => 'Necochea' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 357, 'name' => 'Neuquén' ,'state_id' => 21, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 358, 'name' => 'Nogoyá' ,'state_id' => 7, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 359, 'name' => 'Nonogasta' ,'state_id' => 11, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 360, 'name' => 'Nueve de Julio' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 361, 'name' => 'Obera' ,'state_id' => 13, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 362, 'name' => 'Oberá' ,'state_id' => 13, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 363, 'name' => 'Olavarría' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 364, 'name' => 'Olivos' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 365, 'name' => 'Oncativo' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 366, 'name' => 'Open Door' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 367, 'name' => 'Oran' ,'state_id' => 15, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 368, 'name' => 'Pablo Podestá' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 370, 'name' => 'Palpala' ,'state_id' => 9, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 371, 'name' => 'Pampa del Castillo' ,'state_id' => 4, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 372, 'name' => 'Paraná' ,'state_id' => 7, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 373, 'name' => 'Pasco' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 374, 'name' => 'Paso de los Libres' ,'state_id' => 6, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 375, 'name' => 'Pedro Luro' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 376, 'name' => 'Pehuajó' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 377, 'name' => 'Perdriel' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 378, 'name' => 'Perez' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 379, 'name' => 'Pérez Millán' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 380, 'name' => 'Pergamino' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 381, 'name' => 'Perito Moreno' ,'state_id' => 6, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 382, 'name' => 'Pichanal' ,'state_id' => 15, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 383, 'name' => 'Pico Truncado' ,'state_id' => 6, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 384, 'name' => 'Piedritas' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 385, 'name' => 'Pigue' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 386, 'name' => 'Pilar' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 387, 'name' => 'Pilcomayo' ,'state_id' => 9, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 388, 'name' => 'Pinamar' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 389, 'name' => 'Platanos' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 390, 'name' => 'Plottier' ,'state_id' => 21, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 391, 'name' => 'Pocitos' ,'state_id' => 15, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 392, 'name' => 'Poman' ,'state_id' => 2, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 393, 'name' => 'Posadas' ,'state_id' => 13, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 394, 'name' => 'Pozo del Molle' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 395, 'name' => 'Presidente Roque Sáenz Peña' ,'state_id' => 3, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 396, 'name' => 'Puerto Alumbrera' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 397, 'name' => 'Puerto Belgrano/Bahia Blanca' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 399, 'name' => 'Puerto Deseado' ,'state_id' => 6, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 400, 'name' => 'Puerto Eldorado' ,'state_id' => 13, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 401, 'name' => 'Puerto Galvan/Bahia Blanca' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 402, 'name' => 'Puerto Ingeniero M. Rocca' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 403, 'name' => 'Puerto Lavalle' ,'state_id' => 6, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 404, 'name' => 'Puerto Madero' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 405, 'name' => 'Puerto Madryn' ,'state_id' => 4, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 406, 'name' => 'Puerto Mineral' ,'state_id' => 13, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 407, 'name' => 'Puerto Nacional/Bahia Blanca' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 408, 'name' => 'Puerto Rico' ,'state_id' => 13, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 409, 'name' => 'Puerto Rosales/Bahia Blanca' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 410, 'name' => 'Puerto San Julian' ,'state_id' => 6, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 411, 'name' => 'Puerto Tirol' ,'state_id' => 3, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 412, 'name' => 'Puerto Wanda' ,'state_id' => 13, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 413, 'name' => 'Punta Colorada' ,'state_id' => 14, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 414, 'name' => 'Punta de Vacas' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 416, 'name' => 'Punta Medanos' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 418, 'name' => 'Quebracho/San Lorenzo' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 419, 'name' => 'Quequén' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 420, 'name' => 'Quilmes' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 421, 'name' => 'Rafaela' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 422, 'name' => 'Ramallo' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 423, 'name' => 'Ramos Mejia' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 424, 'name' => 'Ranelagh' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 425, 'name' => 'Rawson' ,'state_id' => 4, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 426, 'name' => 'Recalde' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 427, 'name' => 'Reconquista' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 428, 'name' => 'Remedios de Escalada' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 429, 'name' => 'Resinfor' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 430, 'name' => 'Resistencia' ,'state_id' => 3, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 431, 'name' => 'Rincón de los Sauces' ,'state_id' => 21, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 432, 'name' => 'Rio Colorado' ,'state_id' => 14, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 433, 'name' => 'Río Cuarto' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 435, 'name' => 'Río Gallegos' ,'state_id' => 6, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 436, 'name' => 'Río Grande' ,'state_id' => 20, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 437, 'name' => 'Río Hondo' ,'state_id' => 19, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 438, 'name' => 'Río Mayo' ,'state_id' => 4, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 439, 'name' => 'Rio Segundo' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 440, 'name' => 'Río Tercero' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 441, 'name' => 'Río Turbio' ,'state_id' => 6, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 442, 'name' => 'Rivadavia' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 443, 'name' => 'Rodeo de la Cruz' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 444, 'name' => 'Rodeo del Medio' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 445, 'name' => 'Rojas' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 446, 'name' => 'Rosario' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 447, 'name' => 'Rosario de la Frontera' ,'state_id' => 15, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 448, 'name' => 'Rosario de Lerma' ,'state_id' => 15, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 449, 'name' => 'Rufino' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 450, 'name' => 'Ruiz de Montoya' ,'state_id' => 13, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 451, 'name' => 'Sáenz Peña' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 452, 'name' => 'Salta' ,'state_id' => 15, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 453, 'name' => 'Salto' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 454, 'name' => 'Salto de las Rosas' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 455, 'name' => 'San Agustin' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 456, 'name' => 'San Andres' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 457, 'name' => 'San Andrés de Giles' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 458, 'name' => 'San Antonio de Areco' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 459, 'name' => 'San Antonio de Arredondo' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 460, 'name' => 'San Antonio de Padua' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 461, 'name' => 'San Antonio Este' ,'state_id' => 14, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 462, 'name' => 'San Antonio Oeste' ,'state_id' => 14, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 463, 'name' => 'San Carlos' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 464, 'name' => 'San Carlos Centro' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 465, 'name' => 'San Carlos de Bariloche' ,'state_id' => 14, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 466, 'name' => 'San Fernando' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 467, 'name' => 'San Fernando del Valle de Catamarca' ,'state_id' => 2, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 468, 'name' => 'San Francisco' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 469, 'name' => 'San Francisco Solano' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 470, 'name' => 'San Ignacio' ,'state_id' => 13, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 471, 'name' => 'San Isidro' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 472, 'name' => 'San Javier' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 473, 'name' => 'San Javier' ,'state_id' => 13, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 474, 'name' => 'San Jorge' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 475, 'name' => 'San Jose' ,'state_id' => 7, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 476, 'name' => 'San José de Metán' ,'state_id' => 15, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 477, 'name' => 'San Juan' ,'state_id' => 17, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 478, 'name' => 'San Julian' ,'state_id' => 6, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 479, 'name' => 'San Justo' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 480, 'name' => 'San Lorenzo' ,'state_id' => 10, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 481, 'name' => 'San Luis' ,'state_id' => 16, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 482, 'name' => 'San Martin' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 483, 'name' => 'San Martin' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 484, 'name' => 'San Martin' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 485, 'name' => 'San Martín de los Andes' ,'state_id' => 21, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 486, 'name' => 'San Mateo' ,'state_id' => 19, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 487, 'name' => 'San Miguel' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 488, 'name' => 'San Miguel de Tucumán' ,'state_id' => 21, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 489, 'name' => 'San Miguel del Monte' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 490, 'name' => 'San Nicolás de los Arroyos' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 491, 'name' => 'San Pedro' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 492, 'name' => 'San Pedro' ,'state_id' => 7, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 493, 'name' => 'San Pedro' ,'state_id' => 9, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 494, 'name' => 'San Rafael' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 495, 'name' => 'San Salvador' ,'state_id' => 7, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 496, 'name' => 'San Salvador de Jujuy' ,'state_id' => 9, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 497, 'name' => 'San Sebastián' ,'state_id' => 20, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 498, 'name' => 'San Vicente' ,'state_id' => 13, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 499, 'name' => 'Santa Ana' ,'state_id' => 13, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 500, 'name' => 'Santa Cruz' ,'state_id' => 6, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 501, 'name' => 'Santa Fe' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 502, 'name' => 'Santa Isabel' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 503, 'name' => 'Santa Lucia' ,'state_id' => 17, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 504, 'name' => 'Santa Rosa' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 505, 'name' => 'Santa Rosa' ,'state_id' => 10, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 506, 'name' => 'Santa Teresita' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 507, 'name' => 'Santiago del Estero' ,'state_id' => 19, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 508, 'name' => 'Santo Tome' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 509, 'name' => 'Sarandi' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 510, 'name' => 'Sauce Viejo' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 511, 'name' => 'Sierra Grande' ,'state_id' => 14, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 512, 'name' => 'Soldini' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 513, 'name' => 'Sta. Lucía' ,'state_id' => 17, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 514, 'name' => 'Suipacha' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 515, 'name' => 'Sunchales' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 516, 'name' => 'Tabay' ,'state_id' => 6, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 517, 'name' => 'Tablada' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 518, 'name' => 'Tafi Viejo' ,'state_id' => 21, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 519, 'name' => 'Tandil' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 520, 'name' => 'Tapalque' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 521, 'name' => 'Tartagal' ,'state_id' => 15, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 522, 'name' => 'Temperley' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 523, 'name' => 'Teodelina' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 524, 'name' => 'Ticino' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 525, 'name' => 'Tigre' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 526, 'name' => 'Tornquist' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 527, 'name' => 'Tortuguitas' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 528, 'name' => 'Trelew' ,'state_id' => 4, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 529, 'name' => 'Tres Arroyos' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 530, 'name' => 'Tristan Suarez' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 531, 'name' => 'Tucumán' ,'state_id' => 21, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 532, 'name' => 'Tunuyan' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 533, 'name' => 'Ugarteche' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 534, 'name' => 'Uranga' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 536, 'name' => 'Uriburu' ,'state_id' => 10, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 537, 'name' => 'Ushuaia' ,'state_id' => 20, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 538, 'name' => 'Uspallata' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 539, 'name' => 'Valcheta' ,'state_id' => 14, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 540, 'name' => 'Valentin Alsina' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 541, 'name' => 'Vedia' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 542, 'name' => 'Venado Tuerto' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 543, 'name' => 'Viale' ,'state_id' => 7, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 544, 'name' => 'Vicente López' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 545, 'name' => 'Vichigasta' ,'state_id' => 11, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 546, 'name' => 'Victoria' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 547, 'name' => 'Viedma' ,'state_id' => 14, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 548, 'name' => 'Villa Adelina' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 549, 'name' => 'Villa Allende' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 550, 'name' => 'Villa Ballester' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 551, 'name' => 'Villa Bosch' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 552, 'name' => 'Villa Canas' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 553, 'name' => 'Villa Carlos Paz' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 554, 'name' => 'Villa Constitución' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 555, 'name' => 'Villa del Rosario' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 556, 'name' => 'Villa del Totoral' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 557, 'name' => 'Villa Dolores' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 558, 'name' => 'Villa Dominico' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 559, 'name' => 'Villa Galicia' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 560, 'name' => 'Villa Gesell' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 561, 'name' => 'Villa Gobernador Galvez' ,'state_id' => 18, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 562, 'name' => 'Villa Hernandarias' ,'state_id' => 7, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 563, 'name' => 'Villa Insuperable' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 564, 'name' => 'Villa la Angostura' ,'state_id' => 21, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 565, 'name' => 'Villa Luzuriaga' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 566, 'name' => 'Villa Lynch' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 567, 'name' => 'Villa Madero' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 568, 'name' => 'Villa Maipu' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 569, 'name' => 'Villa Manzano' ,'state_id' => 14, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 570, 'name' => 'Villa Maria' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 571, 'name' => 'Villa Mercedes' ,'state_id' => 16, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 572, 'name' => 'Villa Mercedes' ,'state_id' => 17, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 573, 'name' => 'Villa Nueva' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 574, 'name' => 'Villa Paez' ,'state_id' => 5, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 575, 'name' => 'Villa Regina' ,'state_id' => 14, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 576, 'name' => 'Villa Tesei' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 577, 'name' => 'Villa Zagala' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 578, 'name' => 'Villalonga' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 579, 'name' => 'Virrey del Pino' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 580, 'name' => 'Vista Alegre' ,'state_id' => 21, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 582, 'name' => 'Vistalba' ,'state_id' => 12, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 583, 'name' => 'Wilde' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 584, 'name' => 'Yeruá' ,'state_id' => 7, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 585, 'name' => 'Zapala' ,'state_id' => 21, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 586, 'name' => 'Zárate' ,'state_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['id' => 587, 'name' => 'Zonda' ,'state_id' => 17, 'created_at' => $date, 'updated_at' => $date]

      ];
        foreach($cities as $key => $city) {
          $city['id'] = $key+1;
        }

        DB::table('cities')->insert($cities);
    }
}
